---
- name: Install nginx
  yum: name=nginx state=present 

- name: Copy nginx configuration for drupal
  template: src=drupal.conf dest=/etc/nginx/conf.d/drupal.conf
  notify: restart nginx

- name: insert firewalld rule for nginx
  firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for nginx ssl
  firewalld: port={{ nginx_ssl_port}}/tcp permanent=true state=enabled immediate=yes

- name: http service state
  service: name=nginx state=started enabled=yes
